//
//  DineInWebPresenterTests.swift
//  MyCheckDine
//
//  Created by elad schiller on 8/16/17.
//  Copyright (c) 2017 CocoaPods. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MyCheckDine
import XCTest

struct DineInWebViewControllerSpy: DineInWebDisplayLogic{
  let JSString: String?
  func injectJSToWebView(viewModel: DineInWeb.ViewModel) {
  JSString = viewModel.JS
  }
}
class DineInWebPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var presenter: DineInWebPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupDineInWebPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupDineInWebPresenter()
  {
    presenter = DineInWebPresenter()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
